# 项目开发日志

## HYC(https://github.com/jumphu)

- 搭建了所有的关卡、新手教程和商店场景
- 制作了高地、水体等多种地形
- 制作了6种道具和道具选择及投掷系统
- 完成了关卡切换系统

## LSF(https://github.com/Zephyr-XF)

- 创建了一个全新的角色 prefab，名字是 PlayerRed，用作正式主角
- 按下 J 进行普通攻击，一共有四段
- 按下 K 释放技能1，按下 L 释放技能2，按下 U 释放技能3
- 释放技能 L 会出现时停特写，按下 K 或者 U 可以解除特写。以后会做成击破的瞬间给出特写，然后可以瞬间接上技能，以及时停特效。

## WYC(https://github.com/KumamuKuma)

- 创建了6种怪物
  - 骷髅和哥布林是小怪
  - 蘑菇和守卫是精英
  - 魔鬼是 boss
- 魔鬼做了技能
- 受击音效
- awake 提示

## XLH(https://github.com/Alex-xlh)

- 创建了初版祝福系统页面 prefab，名字是 BlessingSystem
  - 4位梦神会随机出现三位，背景可是视频/图片，有一定动画
  - 使用流程：
    1. 把 BlessingSystem Prefab 拖进场景
    2. 在你想触发祝福的地方调用 `BlessingManager.Instance.TriggerBlessing();`
    3. 点击任意一个选项关闭页面
    4. `BlessingManager.Instance.CloseBlessingUI();` 强制关闭页面
    5. 测试按钮 B
  - 每个神新增了台词
- 完成人对话系统 (DialogueSystem/Shopper1) prefab
  - 将 prefab 拉进场景，在 shopkeep 脚本中挂载相应的 shop canvas 和 shop manager
- 完成碎片回忆系统 (MemorySystem/Trophy draft paper) prefab
  - 直接拉入场景
- 完成开场以及结尾动画 OpeningScene / EndingScene
  - 动画播放完毕后可以设置特定场景跳转

---

## 待办事项（共同编辑）

**场景：**
- 深层梦境与浅层梦境
- 休息房
- 问号房
- 房间串联，制作一场完整游戏

**怪物：**
- 更多种类的 boss 与技能

**角色：**
- 深层梦境与浅层梦境的滤镜

**祝福：**
- 房间偶尔散布的记忆碎片
- 神秘商人
- 受污染的祝福（更加强力，选择会降低清醒值，图片稍微变黑，显得受污染）

**其他：**
- 录制 demo

---

**视频 Demo 链接：** https://www.bilibili.com/video/BV1hAY26YEnP/?spm_id_from=333.1387.upload.video_card.click